[aliases]
iwc = ["--ignore-working-copy"]
np = ["--no-pager"]
pl = ["log", "--template=erichdongubler_preferred()"]
rev-parse = ["log", "--no-graph", "--no-pager", "--color=never", "--template=self.commit_id() ++ '\n'", "--revisions"]
review = ["pl", "--revisions=erichdongubler_stack_review(@)"]
stack = ["np", "pl", "--revisions=erichdongubler_stack(@)"]
stacks = ["pl", "--revisions=erichdongubler_stacks(@)"]
tree = ["pl", "--revisions=mutable() | parents(roots(mutable())) | trunk()"]
wip = ["pl", "--revisions=working_copies()"]

[colors]
"branch" = { fg = "bright green", bold = true }
"branch remote" = "red"
"change_id" = "bright magenta"
"commit_id" = "bright blue"
"description" = "default"
"description placeholder" = "bright black"
"email" = "bright black"
"empty description placeholder" = "bright black"
"empty" = "bright black"
"erichdongubler_dash_fluff" = "bright black"
"git_head" = { fg = "cyan", bold = true }
"git_refs" = "green"
"tag" = { fg = "yellow", bold = true }
"tags" = { fg = "yellow", bold = true }
"timestamp" = "green"
"username" = "bright black"
"working_copy" = { color = "bright", bold = true }
"working_copy branch" = { fg = "bright green", bold = true }
"working_copy branch remote" = { fg = "red", bold = true }
"working_copy change_id" = { bold = true }
"working_copy commit_id" = { bold = true }
"working_copy description placeholder" = { color = "bright black", bold = true, underline = true }
"working_copy description" = { color = "bright white", bold = true, underline = true }
"working_copy git_refs" = {}
"working_copy email" = { bold = true }
"working_copy empty" = { bold = true }
"working_copy empty description placeholder" = { bold = true }
"working_copy timestamp" = { color = "red" }
"working_copy empty timestamp" = { color = "red" }
"working_copy username" = { bold = true }

[revset-aliases]
"erichdongubler_common_ancestor_with_trunk(x)" = "heads(::x & ::trunk())"
"erichdongubler_stack(x)" = "erichdongubler_common_ancestor_with_trunk(x)::x | x:: | trunk()"
"erichdongubler_stacks(x)" = "erichdongubler_common_ancestor_with_trunk(x)::x | descendants(erichdongubler_common_ancestor_with_trunk(x)..x) | trunk()"
"erichdongubler_stack_review(x)" = "erichdongubler_stacks(x) | erichdongubler_common_ancestor_with_trunk(x)::trunk()"

[template-aliases]
"erichdongubler_preferred()" = '''
if(
	root,
	format_root_commit(self),
	label(if(current_working_copy, "working_copy"),
		concat(
			separate(" ",
				label("erichdongubler_dash_fluff", "---"),
				format_short_change_id_with_hidden_and_divergent_info(self),
				format_short_commit_id(commit_id),
				label("erichdongubler_dash_fluff", "-"),
				branches.map(|branch|
					label(
						"branch",
						if(
							branch.remote(),
							label("remote", branch.name() ++ "@" ++ branch.remote()),
							branch.name(),
						),
					)
				),
				tags,
				working_copies,
				git_head,
				if(conflict, label("conflict", "conflict")),
				if(empty, label("empty", "(empty)")),
			),
			"\n",
			separate(" ",
				if(description, description.first_line(), description_placeholder),
				label("username", if(author.name(), author.name(), email_placeholder)),
				format_timestamp(committer.timestamp()),
			),
		),
	),
)
'''
"format_timestamp(timestamp)" = 'label("timestamp", timestamp.ago())'
"format_short_signature(signature)" = "signature.username()"

[ui]
default-command = "stack"
merge-editor = ["p4merge", "$base", "$left", "$right", "$output"]

[user]
name = "Erich Gubler"
email = "erichdongubler@gmail.com"
