[aliases]
stack = ["log", "--revisions", "(main..@):: | (main..@)-"]

[ui]
default-command = "stack"


merge-editor = "p4merge"
merge-tools.p4merge.merge-args = ["$base", "$left", "$right", "-o", "$output"]
[user]
name = "Erich Gubler"
email = "erichdongubler@gmail.com"
